pipelines:
  default:
    - parallel:
      - step:
          name: Lint backend
          image: python:3-alpine
          caches:
            - pip
          script:
            - apk add -U gcc musl-dev
            - pip install black
            - black --check backend/backend backend/surfsara

      - step:
          name: Build frontend
          image: node:12-alpine
          caches:
            - node
          script:
            - cd frontend
            - yarn install
            - yarn build
