version: "3"
services:
    tasker:
        build:
            context: "tasker/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: ${RABBITMQ_USERNAME?RABBITMQ_USERNAME not set}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD?RABBITMQ_PASSWORD not set}
        depends_on:
            - rabbitmq
        command: "entrypoint.sh"

    backend_listen:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: ${RABBITMQ_USERNAME?RABBITMQ_USERNAME not set}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD?RABBITMQ_PASSWORD not set}
        command: "python manage.py listen"

    backend:
        build:
            context: "backend/"
        command: "entrypoint.sh"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 8080:15672
            - 5672
