# Base docker-compose file

version: "3"
services:
    tasker:
        build:
            context: "tasker/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DB_JDBC_URL: "jdbc:postgresql://postgres:5432/surfsara"
            DB_USER: surfsara
            DB_PASSWORD: ""
        depends_on:
            - rabbitmq
            - postgres
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/tasker:/tmp/tasker
        command: "./docker/entrypoint.sh"

    backend_listen:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DJANGO_DB_ENGINE: postgresql_psycopg2
            DJANGO_DB_HOST: postgres
            DJANGO_DB_NAME: surfsara
            DJANGO_DB_USER: surfsara
        depends_on:
            - rabbitmq
            - postgres

    backend:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DJANGO_DB_ENGINE: postgresql_psycopg2
            DJANGO_DB_HOST: postgres
            DJANGO_DB_NAME: surfsara
            DJANGO_DB_USER: surfsara
            SHARES_API_URL: http://tasker:8088/shares/all
        depends_on:
            - rabbitmq
            - postgres
            - tasker

    frontend:
        build:
            context: "frontend/"
        environment:
            BACKEND_BASE_URI: 'http://backend:8000'

    postgres:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: surfsara

    rabbitmq:
        image: rabbitmq:3-management-alpine
