# docker-compose overrides for production build.

version: "3"
services:
    tasker:
        image: git.ia.surfsara.nl:5050/soil/secure-container/tasker${DOCKER_COMPOSE_VERSION_SUFFIX}
        build:
            context: "tasker/"
            dockerfile: "docker/prod.Dockerfile"
        restart: "always"
        environment:
            ENVIRONMENT: "production"
            LOG_LEVEL: "info"

    backend_listen:
        image: git.ia.surfsara.nl:5050/soil/secure-container/backend_listen${DOCKER_COMPOSE_VERSION_SUFFIX}
        build:
            context: "backend/"
            dockerfile: "docker/prod.Dockerfile"
        environment:
            DJANGO_DEBUG: 0
        restart: "always"
        command: "./docker/entrypoint.sh listen"

    backend:
        image: git.ia.surfsara.nl:5050/soil/secure-container/backend${DOCKER_COMPOSE_VERSION_SUFFIX}
        build:
            context: "backend/"
            dockerfile: "docker/prod.Dockerfile"
        environment:
            DJANGO_DEBUG: 0
        volumes:
            - "static:/var/www/html/static"
        restart: "always"
        command: "./docker/entrypoint.sh runserver"

    frontend:
        image: git.ia.surfsara.nl:5050/soil/secure-container/frontend${DOCKER_COMPOSE_VERSION_SUFFIX}
        build:
            context: "frontend/"
            dockerfile: "docker/prod.Dockerfile"
        environment:
            NODE_ENV: "production"
        restart: "always"

    postgres:
        restart: "always"

    rabbitmq:
        restart: "always"

    nginx:
        image: "nginx:1-alpine"
        ports:
            - "127.0.0.1:3000:80"
        depends_on:
            - "frontend"
            - "backend"
        volumes:
            - "static:/var/www/html/static:ro"
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./htpasswd:/etc/nginx/.htpasswd:ro"
        restart: "always"

    mailcatcher:
        image: "jeanberu/mailcatcher"
        ports:
            - "1025:1025"
        restart: "always"

volumes:
    static:
