# docker-compose overrides for production run.

version: "3"
services:
    tasker:
        image: git.ia.surfsara.nl:5050/soil/secure-container/tasker/${DOCKER_IMAGE_REF_NAME}:${DOCKER_IMAGE_TAG}
        restart: "always"
        environment:
            ENVIRONMENT: "production"
            LOG_LEVEL: "info"

    backend_listen:
        image: git.ia.surfsara.nl:5050/soil/secure-container/backend/${DOCKER_IMAGE_REF_NAME}:${DOCKER_IMAGE_TAG}
        environment:
            DJANGO_DEBUG: 0
        restart: "always"
        command: "./docker/entrypoint.sh listen"

    backend:
        image: git.ia.surfsara.nl:5050/soil/secure-container/backend/${DOCKER_IMAGE_REF_NAME}:${DOCKER_IMAGE_TAG}
        environment:
            DJANGO_DEBUG: 0
            DJANGO_EMAIL_URL: "smtp://mh.surfsara.nl:25"
        volumes:
            - "static:/var/www/html/static"
        ports:
            - "127.0.0.1:5000:5000"
        restart: "always"
        command: "./docker/entrypoint.sh runserver"
        depends_on: [rabbitmq, postgres, tasker]

    frontend:
        image: git.ia.surfsara.nl:5050/soil/secure-container/frontend/${DOCKER_IMAGE_REF_NAME}:${DOCKER_IMAGE_TAG}
        environment:
            NODE_ENV: "production"
        ports:
            - "127.0.0.1:3000:3000"            
        restart: "always"

    postgres:
        restart: "always"

    rabbitmq:
        restart: "always"

volumes:
    static:
