version: "3"
services:
    tasker:
        build:
            context: "tasker/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
        restart: always
        depends_on:
            - rabbitmq
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/tasker:/tmp/tasker
        command: "./entrypoint.sh"

    backend_listen:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DJANGO_DB_ENGINE: postgresql_psycopg2
            DJANGO_DB_HOST: postgres
            DJANGO_DB_NAME: surfsara
            DJANGO_DB_USER: surfsara
            DJANGO_DEBUG: 0
        restart: always
        depends_on:
            - rabbitmq
            - postgres
        command: "./entrypoint.sh listen"

    backend:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DJANGO_DB_ENGINE: postgresql_psycopg2
            DJANGO_DB_HOST: postgres
            DJANGO_DB_NAME: surfsara
            DJANGO_DB_USER: surfsara
        depends_on:
            - rabbitmq
            - postgres
        volumes:
            - static:/var/www/html/static
        restart: always
        command: "./entrypoint.sh runserver"

    frontend:
        build:
            context: "frontend/"
        restart: always

    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: surfsara

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 127.0.0.1:8080:15672
        restart: always

    nginx:
        image: nginx:1-alpine
        ports:
            - 127.0.0.1:3000:80
        depends_on:
            - frontend
            - backend
        volumes:
            - static:/var/www/html/static:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./htpasswd:/etc/nginx/.htpasswd:ro
        restart: always

    mailcatcher:
        image: jeanberu/mailcatcher
        ports:
            - 1025:1025
        restart: always

volumes:
    static:
