version: "3"
services:
    tasker:
        build:
            context: "tasker/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
        depends_on:
            - rabbitmq
        command: "./entrypoint.sh"

    backend_listen:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DJANGO_DB_ENGINE: postgresql_psycopg2
            DJANGO_DB_HOST: postgres
            DJANGO_DB_NAME: surfsara
            DJANGO_DB_USER: surfsara
        depends_on:
            - rabbitmq
            - postgres
        command: "./entrypoint.sh listen"

    backend:
        build:
            context: "backend/"
        environment:
            RABBITMQ_HOST: rabbitmq
            RABBITMQ_USERNAME: guest
            RABBITMQ_PASSWORD: guest
            DJANGO_DB_ENGINE: postgresql_psycopg2
            DJANGO_DB_HOST: postgres
            DJANGO_DB_NAME: surfsara
            DJANGO_DB_USER: surfsara
        depends_on:
            - rabbitmq
            - postgres
        command: "./entrypoint.sh runserver"

    postgres:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: surfsara

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 8080:15672
