# Generated by Django 2.2.5 on 2019-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="user", name="webdav_token"),
        migrations.AddField(
            model_name="user",
            name="webdav_password",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
