# Generated by Django 2.2.5 on 2019-09-29 11:12

from django.db import migrations
import surfsara.models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0003_auto_20190924_1337_squashed_0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', surfsara.models.UserManager()),
            ],
        ),
    ]
