# fmt: off
# Generated by Django 2.2.6 on 2019-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0004_auto_20190929_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('author_email', models.TextField()),
                ('approver_email', models.TextField()),
                ('output', models.TextField()),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
