# fmt: off
# Generated by Django 2.2.6 on 2019-10-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0006_auto_20191003_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='dataset',
            field=models.TextField(),
        ),
    ]
