# Generated by Django 2.2.5 on 2019-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0009_auto_20191004_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
