# Generated by Django 2.2.5 on 2019-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0010_auto_20191004_1656")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("data_requested", "Data Requested"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("error", "Error"),
                    ("output_released", "Output Released"),
                    ("request_rejected", "Request Rejected"),
                    ("release_rejected", "Release Rejected"),
                ],
                max_length=255,
            ),
        )
    ]
