# Generated by Django 2.2.6 on 2019-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0011_auto_20191007_1341")]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm", models.TextField()),
                ("dataset", models.TextField()),
            ],
        )
    ]
