# Generated by Django 2.2.6 on 2019-10-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0014_task_review_output")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="review_output",
            field=models.BooleanField(default=True),
        )
    ]
