# Generated by Django 2.2.6 on 2019-10-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0015_auto_20191011_2328"),
        ("surfsara", "0012_auto_20191014_1440"),
    ]

    operations = []
