# Generated by Django 2.2.6 on 2019-10-15 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0016_auto_20191015_0930")]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="registered_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
