# Generated by Django 2.2.6 on 2019-10-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0016_merge_20191019_1540")]

    operations = [migrations.RemoveField(model_name="task", name="review_output")]
