# Generated by Django 2.2.6 on 2019-10-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0017_auto_20191015_1940"),
        ("surfsara", "0017_remove_task_review_output"),
    ]

    operations = []
