# Generated by Django 2.2.6 on 2019-10-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0019_auto_20191020_1338")]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="stream",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surfsara.Permission",
            ),
        ),
    ]
