# Generated by Django 2.2.6 on 2019-10-26 11:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0019_auto_20191020_1338")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="algorithm_content",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        )
    ]
