# Generated by Django 2.2.6 on 2019-10-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0020_auto_20191024_1516")]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="state",
            field=models.CharField(
                choices=[("user permission", "user permission")],
                default="user permission",
                max_length=255,
            ),
        )
    ]
