# Generated by Django 2.2.6 on 2019-10-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0021_permission_state")]

    operations = [
        migrations.RenameField(
            model_name="permission", old_name="state", new_name="permission_type"
        )
    ]
