# Generated by Django 2.2.6 on 2019-10-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0022_auto_20191027_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
