# Generated by Django 2.2.6 on 2019-10-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0020_validate_email_fields_20191026_1213"),
        ("surfsara", "0023_delete_userpermission"),
    ]

    operations = []
