# Generated by Django 2.2.6 on 2019-10-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0024_merge_20191027_2232")]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission_type",
            field=models.CharField(
                choices=[
                    ("user permission", "user permission"),
                    ("stream permission", "stream permission"),
                    ("no permission", "no permission"),
                ],
                default="no permission",
                max_length=255,
            ),
        )
    ]
