# Generated by Django 2.2.6 on 2019-10-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0025_auto_20191027_2232"),
        ("surfsara", "0021_auto_20191026_1137"),
    ]

    operations = []
