# Generated by Django 2.2.6 on 2019-10-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0026_merge_20191027_2323"),
        ("surfsara", "0020_auto_20191026_1539"),
    ]

    operations = []
