# Generated by Django 2.2.6 on 2019-10-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0028_auto_20191027_2355")]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("rejected", "rejected"),
                    ("aborted", "aborted"),
                ],
                default="active",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="status_description",
            field=models.TextField(null=True),
        ),
    ]
