# Generated by Django 2.2.6 on 2019-10-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0028_auto_20191027_2355")]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="etag",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="permission",
            name="permission_type",
            field=models.CharField(
                choices=[
                    ("one off permission", "one off permisson"),
                    ("user permission", "user permission"),
                    ("stream permission", "stream permission"),
                    ("no permission", "no permission"),
                ],
                default="no permission",
                max_length=255,
            ),
        ),
    ]
