# Generated by Django 2.2.6 on 2019-11-02 13:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0031_auto_20191030_1819")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="algorithm_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
