# Generated by Django 2.2.6 on 2019-11-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0031_auto_20191030_1819"),
        ("surfsara", "0029_auto_20191031_1001"),
    ]

    operations = []
