# Generated by Django 2.2.6 on 2019-11-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0032_auto_20191102_1310")]

    operations = []
