# Generated by Django 2.2.6 on 2019-11-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0033_merge_20191103_1545"),
        ("surfsara", "0032_merge_20191102_1630"),
    ]

    operations = []
