# Generated by Django 2.2.6 on 2019-11-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0034_merge_20191103_1954"),
        ("surfsara", "0033_auto_20191104_1511"),
    ]

    operations = []
