# Generated by Django 2.2.6 on 2019-11-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0037_auto_20191107_1158"),
        ("surfsara", "0035_merge_20191104_1512"),
    ]

    operations = []
