# Generated by Django 2.2.6 on 2019-11-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0038_merge_20191107_1946")]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("rejected", "rejected"),
                    ("aborted", "aborted"),
                    ("pending", "pending"),
                ],
                default="pending",
                max_length=255,
            ),
        )
    ]
