# Generated by Django 2.2.6 on 2019-11-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0036_auto_20191107_1052"),
        ("surfsara", "0039_auto_20191107_1948"),
    ]

    operations = []
