# Generated by Django 2.2.6 on 2019-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0040_merge_20191110_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("stream_permission_request", "stream_permission_request"),
                    ("data_requested", "Data Requested"),
                    ("running", "Running"),
                    ("analyzing_algorithm", "Analyzing_algorithm"),
                    ("success", "Success"),
                    ("error", "Error"),
                    ("output_released", "Output Released"),
                    ("request_rejected", "Request Rejected"),
                    ("release_rejected", "Release Rejected"),
                ],
                max_length=255,
            ),
        ),
    ]
