# Generated by Django 2.2.6 on 2019-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("surfsara", "0041_auto_20191110_1758")]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission_type",
            field=models.CharField(
                choices=[
                    ("One specific user permission", "Any algorithm on a Dataset"),
                    ("stream permission", "Run for all data changes"),
                    ("no permission", "no permission"),
                    ("one time permission", "Run once"),
                ],
                default="no permission",
                max_length=255,
            ),
        )
    ]
