# Generated by Django 2.2.7 on 2019-11-28 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0043_auto_20191113_1437"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artefact", models.TextField()),
                ("artefact_etag", models.CharField(max_length=32)),
                (
                    "artefact_info",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("requester_email", models.EmailField(max_length=254)),
                ("approver_email", models.EmailField(max_length=254)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("analyzing", "Artefact is being automatically analysed"),
                            ("pending", "Newly created request"),
                            ("cancelled", "Cancelled by requester"),
                            ("approved", "Approved by approver"),
                            ("rejected", "Rejected by approver"),
                        ],
                        default="analyzing",
                        max_length=255,
                    ),
                ),
                ("registered_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
