# Generated by Django 2.2.7 on 2019-11-28 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0044_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="updated_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
