# Generated by Django 2.2.7 on 2019-11-28 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0045_auto_20191128_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
