# Generated by Django 2.2.7 on 2019-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0047_auto_20191128_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="artefact_etag",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
