# Generated by Django 2.2.7 on 2019-11-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0048_auto_20191128_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="permission_type",
            field=models.CharField(
                default="One specific user permission", max_length=32
            ),
            preserve_default=False,
        ),
    ]
