# Generated by Django 2.2.7 on 2019-12-05 09:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0049_auto_20191129_1346"),
    ]

    operations = [
        migrations.DeleteModel(name="Request",),
        migrations.AddField(
            model_name="permission",
            name="algorithm_report",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="request_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="permission",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="algorithm_etag",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="permission",
            name="permission_type",
            field=models.CharField(
                choices=[
                    ("One specific user permission", "Any algorithm on a Dataset"),
                    ("stream permission", "Run for a stream of data sets"),
                    ("one time permission", "Run once"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="state",
            field=models.CharField(
                choices=[
                    ("analyzing", "Artefact is being automatically analysed"),
                    ("pending", "Newly created request"),
                    ("cancelled", "Cancelled by requester"),
                    ("active", "Approved by approver"),
                    ("rejected", "Rejected or revoked by approver"),
                    ("aborted", "Automatically aborted by DataExchange system"),
                ],
                default="analyzing",
                max_length=255,
            ),
        ),
    ]
