# Generated by Django 2.2.7 on 2019-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0050_auto_20191205_0936"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission", name="dataset", field=models.TextField(null=True),
        ),
    ]
