# Generated by Django 2.2.8 on 2019-12-27 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfsara", "0053_auto_20191206_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress_state",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
