# Generated by Django 2.2.13 on 2020-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0055_auto_20191230_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='algorithm_storage',
            field=models.TextField(default='researchdrive'),
        ),
        migrations.AddField(
            model_name='task',
            name='algorithm_storage',
            field=models.TextField(default='researchdrive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='dataset_storage',
            field=models.TextField(default='researchdrive'),
            preserve_default=False,
        ),
    ]
