# Generated by Django 2.2.13 on 2020-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0056_auto_20200707_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='dataset_storage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='algorithm_storage',
            field=models.TextField(null=True),
        ),
    ]
