# Generated by Django 2.2.13 on 2020-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0057_auto_20200716_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='algorithm_storage',
            field=models.TextField(default='researchdrive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='dataset_storage',
            field=models.TextField(default='researchdrive'),
            preserve_default=False,
        ),
    ]
