# Generated by Django 2.2.16 on 2020-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfsara', '0060_auto_20200910_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('output_released', 'Output Released'), ('release_rejected', 'Release Rejected')], max_length=255),
        ),
    ]
